class Autogenerated {
  String? indexName;
  String? title;
  String? desc;
  int? created;
  int? updated;
  String? createdDate;
  String? updatedDate;
  String? active;
  String? visualizable;
  String? catalogUuid;
  String? source;
  String? orgType;
  List<String>? org;
  List<String>? sector;
  List<Field>? field;
  TargetBucket? targetBucket;
  String? message;
  String? version;
  String? status;
  int? total;
  int? count;
  String? limit;
  String? offset;
  List<Records>? records;

  Autogenerated(
      {this.indexName,
        this.title,
        this.desc,
        this.created,
        this.updated,
        this.createdDate,
        this.updatedDate,
        this.active,
        this.visualizable,
        this.catalogUuid,
        this.source,
        this.orgType,
        this.org,
        this.sector,
        this.field,
        this.targetBucket,
        this.message,
        this.version,
        this.status,
        this.total,
        this.count,
        this.limit,
        this.offset,
        this.records});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    indexName = json['index_name'];
    title = json['title'];
    desc = json['desc'];
    created = json['created'];
    updated = json['updated'];
    createdDate = json['created_date'];
    updatedDate = json['updated_date'];
    active = json['active'];
    visualizable = json['visualizable'];
    catalogUuid = json['catalog_uuid'];
    source = json['source'];
    orgType = json['org_type'];
    org = json['org'].cast<String>();
    sector = json['sector'].cast<String>();
    if (json['field'] != null) {
      field = <Field>[];
      json['field'].forEach((v) {
        field!.add(new Field.fromJson(v));
      });
    }
    targetBucket = json['target_bucket'] != null
        ? new TargetBucket.fromJson(json['target_bucket'])
        : null;
    message = json['message'];
    version = json['version'];
    status = json['status'];
    total = json['total'];
    count = json['count'];
    limit = json['limit'];
    offset = json['offset'];
    if (json['records'] != null) {
      records = <Records>[];
      json['records'].forEach((v) {
        records!.add(new Records.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['index_name'] = this.indexName;
    data['title'] = this.title;
    data['desc'] = this.desc;
    data['created'] = this.created;
    data['updated'] = this.updated;
    data['created_date'] = this.createdDate;
    data['updated_date'] = this.updatedDate;
    data['active'] = this.active;
    data['visualizable'] = this.visualizable;
    data['catalog_uuid'] = this.catalogUuid;
    data['source'] = this.source;
    data['org_type'] = this.orgType;
    data['org'] = this.org;
    data['sector'] = this.sector;
    if (this.field != null) {
      data['field'] = this.field!.map((v) => v.toJson()).toList();
    }
    if (this.targetBucket != null) {
      data['target_bucket'] = this.targetBucket!.toJson();
    }
    data['message'] = this.message;
    data['version'] = this.version;
    data['status'] = this.status;
    data['total'] = this.total;
    data['count'] = this.count;
    data['limit'] = this.limit;
    data['offset'] = this.offset;
    if (this.records != null) {
      data['records'] = this.records!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Field {
  String? name;
  String? id;
  String? type;

  Field({this.name, this.id, this.type});

  Field.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    type = json['type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['id'] = this.id;
    data['type'] = this.type;
    return data;
  }
}

class TargetBucket {
  String? index;
  String? type;
  String? field;

  TargetBucket({this.index, this.type, this.field});

  TargetBucket.fromJson(Map<String, dynamic> json) {
    index = json['index'];
    type = json['type'];
    field = json['field'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['index'] = this.index;
    data['type'] = this.type;
    data['field'] = this.field;
    return data;
  }
}

class Records {
  String? sMonth;
  String? year;
  String? products;
  String? quantity000MetricTonnes;
  String? updatedDate;

  Records(
      {this.sMonth,
        this.year,
        this.products,
        this.quantity000MetricTonnes,
        this.updatedDate});

  Records.fromJson(Map<String, dynamic> json) {
    sMonth = json['_month_'];
    year = json['year'];
    products = json['products'];
    quantity000MetricTonnes = json['quantity_000_metric_tonnes_'];
    updatedDate = json['updated_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_month_'] = this.sMonth;
    data['year'] = this.year;
    data['products'] = this.products;
    data['quantity_000_metric_tonnes_'] = this.quantity000MetricTonnes;
    data['updated_date'] = this.updatedDate;
    return data;
  }
}
